name: release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . -f Dockerfile -t maticinsurance/gocd-agent-with-helm:latest
      - name: Define Docker tag
        run: echo "${GITHUB_REF/refs\/tags\//}" > docker.tag
      - name: Tag docker image
        run: docker tag maticinsurance/gocd-agent-with-helm:latest maticinsurance/gocd-agent-with-helm:$(<docker.tag)
      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push latest image
        run: docker push maticinsurance/gocd-agent-with-helm:latest
      - name: Push tagged image
        run: docker push maticinsurance/gocd-agent-with-helm:$(<docker.tag)
